### PR TITLE
Fix: Airtank now costs 250 steel

### PR DESCRIPTION
**Pull request by eternia16**
### Changes:
* Air Tank now costs 250 steel instead of nothing. Issue #940  (So they're no longer able to be created from thin air haha)

Really simple commit, nothing special.

### CODE REVIEW

**Comment by Andrew-Fall** [comment]
I believe 250 steel is only 1/4th a steel sheet (1000 per)

**Comment by eternia16** [comment]
Could be changed to a higher value if you want

**Comment by JulianCarlosShirey** [comment]
emergeny air tank cost 280 steel so i would say atleast 500 for the air tank or more. you can store 4 time more oxy so making it even more expensive will not pose a problem. maybe around 800 steel?

**Comment by eternia16** [comment]
Sounds fair to me, I've upped the requirements to 850 steel.

**Comment by PsyCommando** [comment]
How did you manage to crash travis? ^^;
Did you use spaces instead of tabs? And did you try compiling it on your end?

**Comment by eternia16** [comment]
I just updated the branch from the DEV, the checks passed before I did that haha.

**Comment by eternia16** [comment]
https://imgur.com/a/BFlOCDE

**Pull request merged**
