### PR TITLE
Dismantable microwave

### PR DESCRIPTION
**Pull request by PsyCommando**
Fixes issue  #784. The conditional had faulty logic. Honestly, the microwave class is a bit confusing and weirdly written, and I wish I could do more, but at least with those changes it can be taken apart now, like it always should have been possible to.

### CODE REVIEW

**Review by ingles98 — APPROVED** [review]
Spaget code gotta be fixed with more spaget heh.
Looks good to go for testing on DEV

**Review by ingles98 — CHANGES_REQUESTED** [review]
Add a changelog entry specifying that people are able to deconstruct it.

**Comment by PsyCommando** [comment]
Didn't feel it was needed since it literally should have always worked. The if statement was just ordered wrong.. And well, it didn't return in a few place it should have.

**Comment by ingles98** [comment]
> Didn't feel it was needed since it literally should have always worked. The if statement was just ordered wrong.. And well, it didn't return in a few place it should ha
thing about it is that people are used to not have it working

**Review by ingles98 — APPROVED** [review]

**Comment by PsyCommando** [comment]
> 
> 
> > Didn't feel it was needed since it literally should have always worked. The if statement was just ordered wrong.. And well, it didn't return in a few place it should ha
> 
> thing about it is that people are used to not have it working

True XD

**Pull request merged**
