### PR TITLE
Un-commented the commented gun code

### PR DESCRIPTION
**Pull request by PsyCommando**
I know brawler spoke about needing to do this, so here.

### CODE REVIEW

**Comment by ourpar** [comment]
if we want them obtainable to everyone we should add them back to the protolathe too, but if they're just going to be event items or something then ignore me

**Comment by PsyCommando** [comment]
I'll try to make them buildable in a bit

**Comment by Kurgis** [comment]
Someone made many of these guns build-able, that's the reason they were commented out. To delete them from the map without causing errors.

**Comment by PsyCommando** [comment]
> 
> 
> Someone made many of these guns build-able, that's the reason they were commented out. To delete them from the map without causing errors.
Sounds good, I was just told by the others they didn't know why.

**Review by michaelchessall — APPROVED** [review]

**Pull request merged**
