### PR TITLE
Fix mirrored mixer and mirrored filters disconnecting on reload

### PR DESCRIPTION
**Pull request by PsyCommando**
Apparently the after_load() proc wasn't overriden for mirrored filters and mixers, so it would set the non-mirrored directions for the nodes to try and attach to other devices after load.

### CODE REVIEW

**Comment by ingles98** [comment]
Was the issue actually just ONE of the directions being disconnected or would it create a runtime therefore not load any direction ? Nevertheless well spotted

**Comment by ingles98** [comment]
Also did you test them ? Just need to confirm that hehe

**Comment by PsyCommando** [comment]
Well, brawler asked me to pr the fix. I posted about it in the private code discussion on discord and showed what was happening.

And there's no way I can test it without the saved variables list. But list or not, its definitely an issue that the initial directions are changed on reload. Since the base class re-sets them, I'm assuming they're not saved. Or if they're saved, they used to get reset to the base class' values instead of the child class' values. Which is definitely not a good thing.

**Comment by ingles98** [comment]
If the PR is ready confirm it and ill get it approved

**Review by ingles98 — APPROVED** [review]

**Comment by ingles98** [comment]
this PR cannot be merged to Main without SoM on a partial dev-to-main merge. @FaurnsGoldberg 
it will produce nasty conflicts

**Comment by PsyCommando** [comment]
Ah crap, I knew I probably should have based it off main..

**Pull request merged**
