### PR TITLE
More Buildables

### PR DESCRIPTION
**Pull request by rhicora**
- Orderable: Janicart Crate
- Barsign access restrictions have been reduced.
- Buildable: Book Binder
- Buildable: Wheelchair
- Buildable: Fire Extinguisher Wall Cabinet
- Buildable: Medical Wall Cabinet
- Buildable: Shipping Wall Cabinet
- Buildable: Fire Safety Wall Cabinet
- Buildable: Linen Bin
- Buildable: Dresser
- Buildable: Dog Bed
- Buildable: Morgue Tray

### CODE REVIEW

**Comment by Zero-Bits** [comment]
Does the linen bin include linens? That could be abused for infinite rags if you have a knife.

**Comment by rhicora** [comment]
What is the morgue tray bug?

**Comment by rhicora** [comment]
I'm not super worried about infinite linens, we don't have a cloth material and the bedsheet crate is still useful because it produces colored sheets.

To make morgue trays stay connected between resets, persist `var/obj/structure/morgue/connected` on the morgue tray (`/obj/structure/m_tray`).

**Comment by Zero-Bits** [comment]
Then we're all clear here.

**Pull request merged**
