### PR TITLE
Peek remap, adds control+wasd

### PR DESCRIPTION
**Pull request by matt81093**
So this changes peeking to shift+alt+dir and adds control+wasd for pointing your char in a direction. I grouped the keys when I was going through them to find stuff easier although the diff looks terrible.

I would use a :cl: but I'm a bit tired to put something there. I need to test this to make sure I didn't accidentally delete something.

### CODE REVIEW

**Comment by Zero-Bits** [comment]
Shift+Dir for peeking would be more consistent with what brawler decided on. Is there a reason you're changing that?

**Comment by matt81093** [comment]
Shift+dir is used by some for other personal macros. Curious about Shift+Ctrl though. Could also remove it entirely, but the issue then becomes people not knowing about it, or those who don't use personal macros. 
I mainly wanted this because modifier keys weren't being used consistently for the peek function.

**Comment by matt81093** [comment]
Erm. Until peeking is fixed, I might remove the macro @Zero-Bits It's apparently causing issues

**Comment by Zero-Bits** [comment]
@matt81093 Righto. I'll wait to hear back from you on that.

**Comment by matt81093** [comment]
Closing this since peeking was removed

**Pull request closed without merging**
