### PR TITLE
Adds department specific softsuits

### PR DESCRIPTION
**Pull request by tacct6**
**features:**
Added softsuit sprites for Engineering, medical, mining, science, and security. They are orderable from cargo for 300 EC 
Changed civilian & emergency softsuit sprites (existing softsuit/emergency softsuit will now look like the new sprites)
All spacesuits in the operations tab now ship in large crates (for consistency)

Department softsuits have minor armor values depending on their department, but don't trust your life with them, they still are softsuits! Essentially newer/poor players will be able to buy a suit that matches stereotypical department colors rather than the generic grey suit now, if spacesuits had tiers, these suits would be tier 1.

***Picture of added sprites:*** https://cdn.discordapp.com/attachments/502972847246016523/506360587798970368/unknown.png

I got generally good feedback of the sprites on the discord, but if there's anything that needs change feel free to mention it here

### CODE REVIEW

**Comment by PsyCommando** [comment]
Have you made species variants for those?

**Comment by ourpar** [comment]
nope, but that could be a good idea for a separate PR. right now any species can fit into the current softsuit without any special sprite change, so i think it's fair to allow it for these suits too.

**Comment by Pandolphina** [comment]
> `	icon_state = "miner_softhelm"
	desc = "A flimsy helmet with extra thick fabric, you still aren't if it'll be enough to protect you."`

**Comment by ourpar** [comment]
should be fixed 9e50a28

**Review by Koollan — APPROVED** [review]
tested in solo environment, works just fine

**Review by Andrew-Fall — APPROVED** [review]
Code checks out and Travis passes.

**Pull request merged**
