### PR TITLE
Printer

### PR DESCRIPTION
**Pull request by UndeadNappist**
You can't build bioprinters anymore - hope you like harvesting organs!

The roborgan printer now uses osmium-carbide plasteel instead of normal steel for organs, so it's hideously expensive now.

### CODE REVIEW

**Comment by ingles98** [comment]
Makes sense

**Comment by SirBloodBuske** [comment]
I feel like you should keep the bio-printer and make it also expensive but that just my opinion

**Comment by rhicora** [comment]
I think it's okay to remove the bioprinter completely, since there's still a roborgan printer for your expensive organ needs.

**Comment by ingles98** [comment]
We'll let @FaurnsGoldberg decide.

**Comment by UndeadNappist** [comment]
Hopefully that changed it to use OCP.

**Comment by FaurnsGoldberg** [comment]
the bioprinter does other things than just organs. removing it without having a full rundown of how all its existing features are done elsewhere is not a good idea

**Pull request merged**
