### PR TITLE
Remove unnecessary undefines

### PR DESCRIPTION
**Pull request by XElectricX**

### CODE REVIEW

**Comment by Zero-Bits** [comment]
This is waiting on the new pipe dispenser recipes.

**Comment by PrPleGoo** [comment]
check the object tree for all pipes

**Comment by XElectricX** [comment]
Trying to add a simple gas injector has been taking up too much of my time so I'll just leave this as is. There are more important things that need to be fixed.

**Comment by PrPleGoo** [comment]
Undeffing these is to prevent the constants from being used anywhere else for any other purpose than pipe construction.

**Comment by FaurnsGoldberg** [comment]
If the defines are only used within the file, undefines seem appropriate to me.

**Pull request closed without merging**
